### ISSUE TITLE
Wither Skeletons have glowing eyes/mouth

### ISSUE THREAD

**Issue by BioMasterZap** [JosiahFu/NetherArchives#2]
On Fabric 1.20.4 with v0.3.4, Wither Skeletons have bright cyan eyes and mouths when the mod is installed.

If this is an intended feature, I did not see it noted anywhere. At the very least, it probably could do with a toggle since it almost looks kinda neat, but not something I'd want.

Screenshot is from a profile with only Nether Archives, Fabric Language Kotlin, and Fabric API and no resource/data packs. Wither Skeletons return to looking normal if the mod is removed.
![2024-02-09_22 39 57](https://github.com/JosiahFu/NetherArchives/assets/42448635/ec894151-ad3f-4d74-a917-376211ee6ab6)

**Comment by JosiahFu** [comment]
Yes, this is an intended feature. I didn't put it in the description because it seemed kind of insignificant, but you bring up a good point about making it configurable. I'll look into that!

**Comment by JosiahFu** [comment]
It's in 0.3.5!
